# Cronjob for running brandbot in production.
#
# SPDX-FileCopyrightText: 2022 Sascha Brawer <sascha@brawer.ch>
# SPDX-License-Identifier: MIT

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: brandbot
  namespace: brandbot
  labels:
    name: brandbot
    toolforge: tool
spec:
  concurrencyPolicy: Forbid  # don't start new jobs while old is still running
  schedule: "39 4 * * *"  # daily at 4:39
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          restartPolicy: OnFailure
          containers:
          - name: brandbot
            workingDir: /data/project/brandbot
            image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
            command: [ "run_brandbot.sh" ]
            resources:
              requests:
                memory: "1.5Gi"
                cpu: "1"
              limits:
                memory: "1.5Gi"
                cpu: "1"
